# =========================
# SonarQube Cloud - bp7-rs
# =========================

sonar.projectKey=Javier-Sinuka_bp7-rs
sonar.organization=javier-sinuka

sonar.projectName=bp7-rs
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

# Código fuente principal
sonar.sources=src

# Tests de integración
sonar.tests=tests

# Coverage Rust generado por cargo-llvm-cov
sonar.rust.lcov.reportPaths=lcov.info

sonar.exclusions=\
target/**,\
.git/**,\
.github/**,\
.cargo/**,\
.devcontainer/**,\
doc/**,\
benches/**,\
examples/**,\
fuzz/**,\
hfuzz-bp7/**,\
**/*.lock

sonar.coverage.exclusions=\
tests/**,\
benches/**,\
examples/**,\
fuzz/**,\
hfuzz-bp7/**,\
build.rs